name: inquire
description: Get to truly know yourself & other people.
publish_to: 'none'

version: 1.2.0+5

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  animations: ^2.0.7
  collection: ^1.16.0
  csv: ^5.0.1
  feather_icons_svg: 0.4.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.2
  flutter_riverpod: ^2.0.2
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  go_router: ^5.1.1
  json_annotation: ^4.7.0
  pressable: ^0.5.0
  url_launcher: ^6.1.6

dev_dependencies:
  build_runner: ^2.1.11
  flutter_launcher_icons_maker: ^0.10.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  json_serializable: ^6.5.3
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  fonts:
    - family: SourceSerif4
      fonts:
        - asset: assets/fonts/SourceSerif4-Regular.ttf
        - asset: assets/fonts/SourceSerif4-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SourceSerif4-Bold.ttf
          weight: 700
  assets:
    - assets/

# `flutter pub run flutter_native_splash:create`
flutter_native_splash:
  color: "#000000"
  image: assets/images/splash.png

# `flutter pub run flutter_launcher_icons_maker:main`
flutter_icons:
  android: true
  ios: true
  macos: true
  windows: true
  web: true
  image_path: "assets/images/icon.png"
